Upgrade version
ADMARIl/halcyon-jetbrains pull request #32
Opened 2023-04-01 11:56 UTC by springmonster

Hi @ADMARIl , I'm trying to resolve #31 .
Could you please to help review this PR?
Thanks!

2023-04-04 15:06 UTC, BrianVia commented
Hey @ADMARIl I feel like I've noticed this isn't a top priority for you (totally understand, we all have lots of things on our plate), I'd love to volunteer as a maintainer if it'd be possible to merge PRs and push new releases of this theme 🙋‍♂️

I believe I speak for the community when I say we really love it and want to help take some load of the work if it'd help get releases for new versions of Jetbrains IDEs pushed out as reasonably close behind the new versions of IDEs.

Thank you again for all the work you've done maintaining this ❤️

2023-04-18 00:58 UTC, ADMARIl commented
@BrianVia Sure, works for me

2023-04-18 01:02 UTC, ADMARIl requested changes

2023-04-18 01:02 UTC, ADMARIl commented on libs/halcyon-jetbrains-2.3.2.jar
I understand your reasoning for adding this, however, I feel that we should avoid having derivative files checked in. Release jars are best saved for adding to releases imo

2023-04-18 03:20 UTC, springmonster commented on libs/halcyon-jetbrains-2.3.2.jar
Yes，you are right. That's not a good solution. I will delete that comment.

2023-04-18 03:35 UTC, springmonster commented on libs/halcyon-jetbrains-2.3.2.jar
Hi @ADMARIl , please help to review.

2023-04-26 21:02 UTC, merged

2023-04-26 21:08 UTC, BrianVia commented
Hey @ADMARIl , are you able to share the publish token with me? My email is brian.via.dev@gmail.com if you want to send a secure link there.

2023-04-27 03:17 UTC, ADMARIl commented
@BrianVia done. Let me know if there's issues publishing the release